name: Input Examples
on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - Gopi
        - CloudEQ
      message:
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greetings (Executed through Command Line (bash))
      run:  |
        echo "${{ github.event.inputs.message }}"
        echo "${{ github.event.inputs.name }}"
    - name: Checkout
      uses: actions/checkout@v3.3.0
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Execute Java Program
      run: |
        java -version
        INPUT_NAME=${{ github.event.inputs.name }}
        INPUT_MESSAGE="${{ github.event.inputs.message}}"
        echo "$INPUT_NAME"
        echo "$INPUT_MESSAGE"
    
